"""
tools/slack_tool.py

MCP Tool: send_slack_report
Sends the doctor's summary report to a Slack channel.
Used in Scenario 2 — different notification channel from email.
"""
import os
from mcp.server.fastmcp import FastMCP

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN", "")
SLACK_CHANNEL_ID = os.getenv("SLACK_CHANNEL_ID", "#doctor-notifications")


def register(mcp: FastMCP):

    @mcp.tool()
    async def send_slack_report(
        doctor_name: str,
        report_text: str,
        channel: str = "",
    ) -> str:
        """
        Send the doctor's appointment summary report to Slack.

        Args:
            doctor_name: Doctor's name (for the Slack message header)
            report_text: The full report text to send
            channel: Slack channel ID or name (optional, uses default if not provided)

        Returns:
            Success or failure message.
        """
        import httpx

        target_channel = channel or SLACK_CHANNEL_ID

        # Build rich Slack Block Kit message (looks much better than plain text)
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"Report for {doctor_name}",
                    "emoji": True,
                },
            },
            {"type": "divider"},
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": _format_for_slack(report_text),
                },
            },
            {"type": "divider"},
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "🤖 Generated by *DOBBE Health AI* | Powered by MCP Agent",
                    }
                ],
            },
        ]

        try:
            async with httpx.AsyncClient() as client:
                resp = await client.post(
                    "https://slack.com/api/chat.postMessage",
                    headers={
                        "Authorization": f"Bearer {SLACK_BOT_TOKEN}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "channel": target_channel,
                        "blocks": blocks,
                        "text": f"Report for Dr. {doctor_name}",  # fallback for notifications
                    },
                    timeout=15,
                )
            data = resp.json()
            if data.get("ok"):
                return f"✅ Report sent to Slack channel {target_channel}"
            else:
                return f"⚠️ Slack error: {data.get('error', 'unknown error')}"
        except Exception as e:
            return f"⚠️ Slack send failed: {str(e)}"


async def send_slack_direct(doctor_name: str, report_text: str, channel: str = "") -> str:
    """
    Standalone function to send a Slack report directly (not via LLM tool call).
    Called from the /report/send-slack endpoint to guarantee delivery.
    """
    import httpx

    target_channel = channel or SLACK_CHANNEL_ID
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"Report for {doctor_name}",
                "emoji": True,
            },
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": _format_for_slack(report_text),
            },
        },
        {"type": "divider"},
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "🤖 Generated by *DOBBE Health AI* | Powered by MCP Agent",
                }
            ],
        },
    ]

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                "https://slack.com/api/chat.postMessage",
                headers={
                    "Authorization": f"Bearer {SLACK_BOT_TOKEN}",
                    "Content-Type": "application/json",
                },
                json={
                    "channel": target_channel,
                    "blocks": blocks,
                    "text": f"Report for Dr. {doctor_name}",
                },
                timeout=15,
            )
        data = resp.json()
        if data.get("ok"):
            return f"✅ Report sent to Slack channel {target_channel}"
        else:
            return f"⚠️ Slack error: {data.get('error', 'unknown error')}"
    except Exception as e:
        return f"⚠️ Slack send failed: {str(e)}"


def _format_for_slack(text: str) -> str:
    """Convert plain text report to Slack markdown format"""
    lines = text.split("\n")
    formatted = []
    for line in lines:
        if line.startswith("  •"):
            formatted.append(line)  # bullet stays as-is
        elif line.startswith("📊") or line.startswith("📋") or line.startswith("🔍"):
            formatted.append(f"*{line}*")  # bold headers
        elif "─" in line:
            formatted.append("")  # skip divider lines, Slack has its own
        else:
            formatted.append(line)
    return "\n".join(formatted)
